-- Enhance AUDIT_LOGS table to match the UI and support comprehensive auditing
ALTER TABLE `AUDIT_LOGS` DROP CHECK `chk_audit_action`;
ALTER TABLE `AUDIT_LOGS` MODIFY COLUMN `user_id` BIGINT UNSIGNED NULL;
ALTER TABLE `AUDIT_LOGS` ADD COLUMN `ip_address` VARCHAR(45) NULL;
ALTER TABLE `AUDIT_LOGS` ADD COLUMN `status` VARCHAR(20) NULL;
ALTER TABLE `AUDIT_LOGS` ADD COLUMN `description` TEXT NULL;
