CREATE TABLE IF NOT EXISTS `STOCKTAKE_LINE_SERIALS` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `stocktake_line_id` BIGINT UNSIGNED NOT NULL,
  `serial_number_id` BIGINT UNSIGNED NULL,
  `serial_number` VARCHAR(100) NOT NULL,
  `scan_status` VARCHAR(30) NOT NULL DEFAULT 'MATCHED',
  `note` VARCHAR(255) NULL,
  CONSTRAINT `fk_stl_serial_line` FOREIGN KEY (`stocktake_line_id`) REFERENCES `STOCKTAKE_LINES` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_stl_serial_id` FOREIGN KEY (`serial_number_id`) REFERENCES `SERIAL_NUMBERS` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
