CREATE TABLE IF NOT EXISTS `ASSEMBLY_ORDER_SERIALS` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `assembly_order_id` BIGINT UNSIGNED NOT NULL,
  `target_variant_id` BIGINT UNSIGNED NOT NULL,
  `target_serial` VARCHAR(100) NOT NULL,
  `component_variant_id` BIGINT UNSIGNED NOT NULL,
  `component_serial` VARCHAR(100) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  `installed_at` DATETIME NULL,
  `removed_at` DATETIME NULL,
  `source_repair_id` BIGINT UNSIGNED NULL,
  `removed_by_repair_id` BIGINT UNSIGNED NULL,
  `replaced_by_serial` VARCHAR(100) NULL,
  `note` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_aos_order` FOREIGN KEY (`assembly_order_id`) REFERENCES `ASSEMBLY_ORDERS` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aos_target_variant` FOREIGN KEY (`target_variant_id`) REFERENCES `PRODUCT_VARIANTS` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_aos_component_variant` FOREIGN KEY (`component_variant_id`) REFERENCES `PRODUCT_VARIANTS` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `status` VARCHAR(30) NOT NULL DEFAULT ''ACTIVE'' AFTER `component_serial`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'status'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `installed_at` DATETIME NULL AFTER `status`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'installed_at'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `removed_at` DATETIME NULL AFTER `installed_at`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'removed_at'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `source_repair_id` BIGINT UNSIGNED NULL AFTER `removed_at`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'source_repair_id'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `removed_by_repair_id` BIGINT UNSIGNED NULL AFTER `source_repair_id`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'removed_by_repair_id'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `replaced_by_serial` VARCHAR(100) NULL AFTER `removed_by_repair_id`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'replaced_by_serial'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = (
  SELECT IF(COUNT(*) = 0,
    'ALTER TABLE `ASSEMBLY_ORDER_SERIALS` ADD COLUMN `note` TEXT NULL AFTER `replaced_by_serial`',
    'SELECT 1'
  )
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ASSEMBLY_ORDER_SERIALS'
    AND COLUMN_NAME = 'note'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE `ASSEMBLY_ORDER_SERIALS`
SET `status` = 'ACTIVE'
WHERE `status` IS NULL OR TRIM(`status`) = '';

UPDATE `ASSEMBLY_ORDER_SERIALS`
SET `installed_at` = COALESCE(`created_at`, CURRENT_TIMESTAMP)
WHERE `installed_at` IS NULL;
