import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import AdminLayout from '../../components/layout/AdminLayout';
import * as warehouseApi from '../../api/warehouseApi';
import styles from './CreateStocktakePage.module.css';
import Toast from '../../components/ui/Toast/Toast';

function CreateStocktakePage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [warehouses, setWarehouses] = useState([]);

  const [formData, setFormData] = useState({
    purpose: 'Kiểm kê vật tư hàng hóa định kỳ',
    code: 'KKK00002', // Ideally auto-generated by backend
    warehouseId: searchParams.get('warehouseId') || 'all',
    toDate: searchParams.get('toDate') || new Date().toISOString().split('T')[0],
    createdDate: new Date().toISOString().slice(0, 16),
    conclusion: '',
    isProcessed: false,
    isValueStocktake: false
  });

  const [isSaved, setIsSaved] = useState(false);
  const [toast, setToast] = useState({ isVisible: false, type: 'success', message: '' });

  const showToast = (type, message) => {
    setToast({ isVisible: true, type, message });
  };

  const [lines] = useState([
    { id: 1, itemCode: 'VT001', sku: 'SKU-BP-001', itemName: 'Bàn phím cơ', unit: 'Cái', bookQty: 10, countQty: 10, diffQty: 0, good100: 10, bad: 0, lost: 0, action: 'Không xử lý' }
  ]);

  const [isParticipantsExpanded, setIsParticipantsExpanded] = useState(false);
  const [participants, setParticipants] = useState([
    { name: 'Nguyễn Văn A', title: 'Thủ kho', represent: 'Kho thành phẩm' }
  ]);

  useEffect(() => {
    // Load warehouses
    const loadData = async () => {
      try {
        const response = await warehouseApi.getWarehouses();
        const data = response?.data?.data?.content || response?.data?.data || response?.data || [];
        setWarehouses(Array.isArray(data) ? data : []);
      } catch (err) {
        console.error('Failed to load warehouses', err);
      }
    };
    loadData();
  }, []);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleCancel = () => {
    navigate('/stocktakes');
  };



  const handleSaveAndClose = () => {
    // navigate and pass state for toast
    navigate('/stocktakes', { state: { toastMessage: 'Lưu và Đóng thành công!', toastType: 'success' } });
  };

  return (
    <AdminLayout>
      <div className={styles.pageBody}>

        {/* Page Header */}
        <div className={styles.pageHeader}>
          <button className={styles.backBtn} onClick={handleCancel} title="Quay lại">
            <i className="bi bi-arrow-left"></i>
            <h1 className={styles.pageTitle}>
              Bảng kiểm kê vật tư, hàng hóa {formData.code}
            </h1>
          </button>
          {formData.isProcessed && (
            <div className={styles.processedStamp}>Đã xử lý chênh lệch</div>
          )}
        </div>

        {/* Master Data Section */}
        <div className={styles.masterForm}>
          <div className={styles.formGridLeft}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Mục đích</label>
              <input type="text" className={styles.formInput} name="purpose" value={formData.purpose} onChange={handleChange} />
            </div>
            <div className={styles.formRow}>
              <div className={styles.formGroup}>
                <label className={styles.formLabel}>Kiểm kê kho</label>
                <select className={styles.formSelect} name="warehouseId" value={formData.warehouseId} onChange={handleChange}>
                  <option value="all">Tất cả</option>
                  {warehouses.map(wh => (
                    <option key={wh.id} value={wh.id}>{wh.name}</option>
                  ))}
                </select>
              </div>
              <div className={styles.formGroup}>
                <label className={styles.formLabel}>Đến ngày</label>
                <input type="date" className={styles.formInput} name="toDate" value={formData.toDate} onChange={handleChange} />
              </div>
            </div>

          </div>

          <div className={styles.formGridRight}>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Số</label>
              <input type="text" className={styles.formInput} value={formData.code} disabled />
            </div>
            <div className={styles.formGroup}>
              <label className={styles.formLabel}>Ngày</label>
              <input type="datetime-local" className={styles.formInput} name="createdDate" value={formData.createdDate} onChange={handleChange} />
            </div>
          </div>
        </div>

        {/* Participants Section */}
        <div
          className={styles.sectionHeader}
          onClick={() => setIsParticipantsExpanded(!isParticipantsExpanded)}
        >
          <i className={isParticipantsExpanded ? "bi bi-caret-down-fill" : "bi bi-caret-right-fill"}></i> Thành viên tham gia
        </div>

        {isParticipantsExpanded && (
          <div className={styles.participantsSection}>
            <div className={styles.tableContainer}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th style={{ width: '5%', textAlign: 'center' }}>#</th>
                    <th style={{ width: '35%' }}>HỌ VÀ TÊN</th>
                    <th style={{ width: '30%' }}>CHỨC DANH</th>
                    <th style={{ width: '30%' }}>ĐẠI DIỆN</th>
                  </tr>
                </thead>
                <tbody>
                  {participants.map((p, idx) => (
                    <tr key={idx}>
                      <td style={{ textAlign: 'center' }}>{idx + 1}</td>
                      <td>
                        <input type="text" value={p.name} onChange={(e) => {
                          const newP = [...participants];
                          newP[idx].name = e.target.value;
                          setParticipants(newP);
                        }} />
                      </td>
                      <td>
                        <input type="text" value={p.title} onChange={(e) => {
                          const newP = [...participants];
                          newP[idx].title = e.target.value;
                          setParticipants(newP);
                        }} />
                      </td>
                      <td>
                        <input type="text" value={p.represent} onChange={(e) => {
                          const newP = [...participants];
                          newP[idx].represent = e.target.value;
                          setParticipants(newP);
                        }} />
                      </td>
                    </tr>
                  ))}
                  {participants.length === 0 && (
                    <tr>
                      <td colSpan={4} style={{ textAlign: 'center', padding: '16px', color: '#64748b' }}>
                        Chưa có thành viên nào
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            <div className={styles.tableFooterActions} style={{ marginBottom: '16px' }}>
              <button
                className={styles.btnOutline}
                onClick={() => setParticipants([...participants, { name: '', title: '', represent: '' }])}
              >
                Thêm dòng
              </button>
              <button
                className={styles.btnOutline}
                onClick={() => setParticipants([])}
              >
                Xóa hết dòng
              </button>
            </div>
          </div>
        )}

        {/* Details Section */}
        <div className={styles.detailSection}>
          <div style={{ fontWeight: 600, marginBottom: '12px', color: '#334155' }}>Vật tư, hàng hóa cần điều chỉnh</div>
          <div className={styles.detailToolbar}>
            <label className={styles.toolbarCheckbox}>
              <input type="checkbox" name="isValueStocktake" checked={formData.isValueStocktake} onChange={handleChange} />
              Kiểm kê giá trị
            </label>
            <div className={styles.toolbarActions}>
              <button className={styles.btnOutline}>Lấy lại số tồn</button>
              <button className={styles.btnOutline}>Tải danh sách VTHH</button>
              <button className={styles.btnOutline}>Nhập kết quả từ Excel</button>
            </div>
          </div>

          <div className={styles.tableContainer}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th rowSpan={2} style={{ width: '8%' }}>MÃ HÀNG</th>
                  <th rowSpan={2} style={{ width: '10%' }}>SKU</th>
                  <th rowSpan={2} style={{ width: '15%' }}>TÊN HÀNG</th>
                  <th rowSpan={2} style={{ width: '7%' }}>ĐVT</th>
                  <th colSpan={3}>SỐ LƯỢNG</th>
                  <th colSpan={3}>PHẨM CHẤT</th>
                  <th rowSpan={2} style={{ width: '12%' }}>XỬ LÝ</th>
                </tr>
                <tr>
                  <th>THEO HỆ THỐNG</th>
                  <th>THEO KIỂM KÊ</th>
                  <th>CHÊNH LỆCH</th>
                  <th>CÒN TỐT 100%</th>
                  <th>KÉM PHẨM CHẤT</th>
                  <th>MẤT PHẨM CHẤT</th>
                </tr>
              </thead>
              <tbody>
                {lines.map((line, idx) => (
                  <tr key={idx}>
                    <td>{line.itemCode}</td>
                    <td>{line.sku}</td>
                    <td>{line.itemName}</td>
                    <td>{line.unit}</td>
                    <td className={styles.numberCol}>{line.bookQty}</td>
                    <td className={styles.numberCol}>
                      <input type="number" value={line.countQty} onChange={() => { }} />
                    </td>
                    <td className={styles.numberCol}>{line.diffQty}</td>
                    <td className={styles.numberCol}>
                      <input type="number" value={line.good100} onChange={() => { }} />
                    </td>
                    <td className={styles.numberCol}>
                      <input type="number" value={line.bad} onChange={() => { }} />
                    </td>
                    <td className={styles.numberCol}>
                      <input type="number" value={line.lost} onChange={() => { }} />
                    </td>
                    <td>
                      <select value={line.action} onChange={() => { }}>
                        <option value="Không xử lý">Không xử lý</option>
                        <option value="Xử lý chênh lệch">Xử lý chênh lệch</option>
                      </select>
                    </td>
                  </tr>
                ))}
                <tr style={{ fontWeight: 600, backgroundColor: '#f8fafc' }}>
                  <td colSpan={4}>Tổng</td>
                  <td className={styles.numberCol}>10</td>
                  <td className={styles.numberCol}>10</td>
                  <td className={styles.numberCol}>0</td>
                  <td className={styles.numberCol}>10</td>
                  <td className={styles.numberCol}>0</td>
                  <td className={styles.numberCol}>0</td>
                  <td></td>
                </tr>
              </tbody>
            </table>
          </div>

          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
            <span style={{ fontSize: '13px', color: '#64748b' }}>Tổng số: {lines.length} bản ghi</span>
            <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
              <select className={styles.formSelect} style={{ width: 'auto' }}>
                <option>50 bản ghi trên 1 trang</option>
              </select>
            </div>
          </div>

          <div className={styles.tableFooterActions}>
            <button className={styles.btnOutline}>Thêm dòng</button>
            <button className={styles.btnOutline}>Xóa hết dòng</button>
          </div>
        </div>

        {/* Conclusion Section */}
        <div className={styles.conclusionSection}>
          <div className={styles.formGroup}>
            <label className={styles.formLabel}>Kết luận</label>
            <textarea className={styles.textareaControl} name="conclusion" value={formData.conclusion} onChange={handleChange}></textarea>
          </div>

          <label className={styles.toolbarCheckbox} style={{ marginBottom: '8px' }}>
            <input type="checkbox" name="isProcessed" checked={formData.isProcessed} onChange={handleChange} />
            Đã xử lý chênh lệch
          </label>

          <div className={styles.formGroup}>
            <label className={styles.formLabel} style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <i className="bi bi-paperclip"></i> Đính kèm <span style={{ color: '#94a3b8', fontWeight: 400 }}>Dung lượng tối đa 5MB</span>
            </label>
            <div className={styles.attachmentZone}>
              Kéo/thả tệp vào đây hoặc bấm vào đây
            </div>
          </div>
        </div>

      </div>

      {/* Fixed Footer */}
      {isSaved ? (
        <div className={styles.pageFooterView}>
          <div className={styles.footerViewLeft}>
            <button className={styles.btnViewIcon} title="Trước"><i className="bi bi-chevron-left"></i></button>
            <button className={styles.btnViewIcon} title="Sau"><i className="bi bi-chevron-right"></i></button>
            <button className={styles.btnViewOutline}>Lập phiếu xuất</button>
            <button className={styles.btnViewOutline}>Lập phiếu nhập</button>
            <button className={styles.btnViewPrimary} onClick={() => setIsSaved(false)}>Sửa</button>
          </div>
          <div className={styles.footerViewRight}>
            <button className={styles.btnViewText}>
              <i className="bi bi-printer"></i> In <i className="bi bi-caret-down-fill" style={{ fontSize: '10px', marginLeft: '4px' }}></i>
            </button>
            <button className={styles.btnViewText}>
              <i className="bi bi-info-circle"></i> Tiện ích
            </button>
          </div>
        </div>
      ) : (
        <div className={styles.pageFooter}>
          <div className={styles.footerLeft}>
            <button className={`${styles.btnFooter} ${styles.btnFooterCancel}`} onClick={handleCancel}>Hủy bỏ</button>
          </div>
          <div className={styles.footerRight}>
            <button className={`${styles.btnFooter} ${styles.btnFooterDraft}`} onClick={() => alert('Đã lưu nháp!')}>
              <i className="bi bi-box-arrow-in-down"></i> Lưu tạm
            </button>
            <button className={`${styles.btnFooter} ${styles.btnFooterSave}`} onClick={() => {
              setIsSaved(true);
              showToast('success', 'Lưu lại thành công!');
            }}>
              <i className="bi bi-check-circle"></i> Lưu lại
            </button>
            <button className={`${styles.btnFooter} ${styles.btnFooterPost}`} onClick={handleSaveAndClose}>
              <i className="bi bi-printer"></i> Lưu và Đóng
            </button>
          </div>
        </div>
      )}
      <Toast
        isVisible={toast.isVisible}
        type={toast.type}
        message={toast.message}
        onClose={() => setToast({ ...toast, isVisible: false })}
      />
    </AdminLayout>
  );
}

export default CreateStocktakePage;
